# Generated by Django 4.2.17 on 2025-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                error_messages={
                    'invalid': 'Enter a valid email address.',
                    'unique': 'This email is already registered.',
                },
                max_length=254,
                unique=True,
                verbose_name='Email',
            ),
        ),
    ]
