# Generated by Django 4.2.17 on 2025-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True
            ),
        ),
    ]
