# Generated by Django 4.2.17 on 2025-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                blank=True,
                help_text='Optional. 150 characters or fewer.',
                max_length=150,
                null=True,
                unique=True,
                verbose_name='Username',
            ),
        ),
    ]
