# Generated by Django 4.2.17 on 2025-05-07 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='date joined'
            ),
        ),
    ]
