# Generated by Django 4.2.17 on 2025-05-13 13:22

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Please upload a PNG or JPG file.',
                null=True,
                upload_to='users/',
                validators=[
                    utils.validators.validate_image.validate_image_extension,
                    utils.validators.validate_image.validate_image_size,
                ],
                verbose_name='Image',
            ),
        ),
    ]
