services:
  db:
    container_name: postgres-dev-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db
      - LC_ALL=C.UTF-8
    ports:
      - "5430:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local