default_language_version:
  python: python3.12

default_stages: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [ python ]
        pass_filenames: false
      # - id: secure
      #   name: secure
      #   entry: make secure
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      - id: mytype
        name: mytype
        entry: make type-check
        language: system
        types: [python]
        pass_filenames: false
      # - id: test
      #   name: test
      #   entry: make test
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      - id: django-check
        name: Run Django Check
        entry: python app/manage.py check
        language: system
        pass_filenames: false
        types: [python]
      - id: migrations-check
        name: Ensure Migrations Are Up-to-Date
        entry: python app/manage.py makemigrations --dry-run --check
        language: system
        pass_filenames: false
        types: [python]
