services:
  postgres:
    container_name: postgres-db
    image: postgres:15-alpine 
    restart: always
    environment:
      - LC_ALL=C.UTF-8
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  web: &web
    container_name: mireldar_web
    build: .
    env_file:
      - .env
    user: "${UID}:${GID}"
    volumes:
      - ./app:/code
      - ./app/static:/code/static
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  nginx:
    image: jwilder/nginx-proxy
    container_name: mireldar_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/sites/mireldar.com.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/code/static
      - media_data:/code/media
    ports:
      - "80:80"
    depends_on:
      - web 

volumes:
  db:
  media_data:

networks:
  nginx-proxy:
    external: true
