version: '3.5'

services:
  postgres:
    container_name: postgres-db
    image: postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

volumes:
    postgres: