[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = "(migrations|settings|__init__\\.py)"

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
force_grid_wrap = 0
skip = ["migrations", "env", "settings"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
recursive = true
in-place = true
exclude = ["__init__.py", "settings", "migrations", "apps.py"]

[tool.autopep8]
max_line_length = 90
in-place = true
recursive = true
aggressive = 2
exclude = "__init__.py,settings,migrations,apps.py"

[tool.flake8]
max-line-length = 88
select = ["C", "E226", "F", "W", "B", "B9"]
exclude = [".git", "__pycache__", ".venv", "migrations", "__init__.py", "settings", "apps.py"]
ignore = ["E203", "E501", "W503", "C812", "E731", "F811"]
max-complexity = 5
max-cognitive-complexity = 5

[tool.bandit]
severity = "high"
confidence = "high"
skips = ["B311", "B404"]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
mypy_path = "app"
exclude = ["app/.*/migrations/.*"]
python_version = "3.12"
warn_unused_ignores = true
warn_return_any = true
show_error_codes = true
warn_unused_configs = true
ignore_missing_imports = true
no_site_packages = false

[tool.django-stubs]
django_settings_module = "config.settings.dev"