from .about_us import AboutUs
from .banner import Banner
from .contact import Contact
from .faq import Faq
from .newsletter import Newsletter
from .site_settings import SiteSettings
from .statistics import StatisticalIndicator
from .testimoinal import Testimoinal
from .who_we_are import WhoWeAre
