from .newsletter import Newsletter
from .contact import Contact
from .faq import Faq
from .site_settings import SiteSettings
from .statistics import StatisticalIndicator
from .about_us import AboutUs
from .who_we_are import WhoWeAre
from .testimoinal import Testimoinal
from .banner import Banner