# Generated by Django 4.2.17 on 2025-04-30 09:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        unique=True,
                        verbose_name='Məqalə başlığı',
                    ),
                ),
                (
                    'title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Məqalə başlığı',
                    ),
                ),
                (
                    'title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Məqalə başlığı',
                    ),
                ),
                (
                    'title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Məqalə başlığı',
                    ),
                ),
                (
                    'short_description',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=200,
                        verbose_name='Qısa məzmun',
                    ),
                ),
                (
                    'short_description_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=200,
                        null=True,
                        verbose_name='Qısa məzmun',
                    ),
                ),
                (
                    'short_description_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=200,
                        null=True,
                        verbose_name='Qısa məzmun',
                    ),
                ),
                (
                    'short_description_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=200,
                        null=True,
                        verbose_name='Qısa məzmun',
                    ),
                ),
                (
                    'content',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name='Məqalə mətni'
                    ),
                ),
                (
                    'content_az',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name='Məqalə mətni'
                    ),
                ),
                (
                    'content_en',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name='Məqalə mətni'
                    ),
                ),
                (
                    'content_ru',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        null=True, verbose_name='Məqalə mətni'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='blogs/', verbose_name='Cover foto'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.',
                        max_length=500,
                        null=True,
                        verbose_name='Link adı',
                    ),
                ),
                ('view_count', models.IntegerField(default=0, editable=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('DF', 'Draft'), ('PB', 'Published')],
                        default='PB',
                        max_length=2,
                    ),
                ),
                (
                    'published_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Paylaşım tarixi'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Məqalə',
                'verbose_name_plural': 'Məqalələr',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 150-dir.',
                        max_length=150,
                        unique=True,
                        verbose_name='Kateqoriya adı',
                    ),
                ),
                (
                    'name_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 150-dir.',
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name='Kateqoriya adı',
                    ),
                ),
                (
                    'name_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 150-dir.',
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name='Kateqoriya adı',
                    ),
                ),
                (
                    'name_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 150-dir.',
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name='Kateqoriya adı',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.',
                        max_length=500,
                        null=True,
                        verbose_name='Link adı',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Məqalə kateqoriyası',
                'verbose_name_plural': 'Məqalə kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Bloq rəyi')),
            ],
            options={
                'verbose_name': 'Məqalə rəyi',
                'verbose_name_plural': 'Məqalə rəyləri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'view_ip',
                    models.GenericIPAddressField(
                        editable=False, verbose_name='IP ünvanı'
                    ),
                ),
            ],
            options={
                'verbose_name': 'IP ünvanı',
                'verbose_name_plural': 'IP ünvanları',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 80-dir.',
                        max_length=80,
                        unique=True,
                        verbose_name='Tag',
                    ),
                ),
                (
                    'name_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 80-dir.',
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name='Tag',
                    ),
                ),
                (
                    'name_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 80-dir.',
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name='Tag',
                    ),
                ),
                (
                    'name_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 80-dir.',
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name='Tag',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.',
                        max_length=500,
                        null=True,
                        verbose_name='Link adı',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Məqalə teqi',
                'verbose_name_plural': 'Məqalə teqləri',
            },
        ),
    ]
