from .about_us_seo import AboutUsPageSeoFactory
from .appintment_page_seo import AppointmentPageSeoFactory
from .blogs_page_seo import BlogsPageSeoFactory
from .contact_page_seo import ContactPageSeoFactory
from .coworker import CoworkerFactory
from .download import DownloadFactory
from .faq_page_seo import FaqPageSeoFactory
from .service import ServiceFactory
from .user import UserFactory
from .why_choose_us import WhyChooseUsFactory
