from .blog.blog import BlogFactory
from .blog.category import CategoryFactory
from .blog.comment import CommentFactory
from .blog.ip import IPFactory
from .blog.tag import TagFactory
from .core.about_us import AboutUsFactory
from .core.banner import BannerFactory
from .core.contact import ContactFactory
from .core.faq import FaqFactory
from .core.indicator import StatisticalIndicatorFactory
from .core.newsletter import NewsletterFactory
from .core.site_settings import SiteSettingsFactory
from .core.testimonial import TestimonialFactory
from .core.who_we_are import WhoWeAreFactory
from .seo.about_us_page_seo import AboutUsPageSeoFactory
from .seo.appintment_page_seo import AppointmentPageSeoFactory
from .seo.blog_detail_page_seo import BlogDetailPageSeoFactory
from .seo.blogs_page_seo import BlogsPageSeoFactory
from .seo.contact_page_seo import ContactPageSeoFactory
from .seo.faq_page_seo import FaqPageSeoFactory
from .seo.home_page_seo import HomePageSeoFactory
from .seo.service_detail_page_seo import ServiceDetailPageSeoFactory
from .seo.services_page_seo import ServicesPageSeoFactory
from .service.coworker import CoworkerFactory
from .service.download import DownloadFactory
from .service.service import ServiceFactory
from .service.why_choose_us import WhyChooseUsFactory
from .user.user import UserFactory
