# Generated by Django 4.2.17 on 2025-05-15 12:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/about-us/')),
            ],
            options={
                'verbose_name': 'About Us Page SEO',
                'verbose_name_plural': 'About Us Page SEO',
            },
        ),
        migrations.CreateModel(
            name='AppointmentPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/appointment/')),
            ],
            options={
                'verbose_name': 'Appointment Page SEO',
                'verbose_name_plural': 'Appointment Page SEO',
            },
        ),
        migrations.CreateModel(
            name='BlogsPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/blogs/')),
            ],
            options={
                'verbose_name': 'Blogs Page SEO',
                'verbose_name_plural': 'Blogs Page SEO',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/contact/')),
            ],
            options={
                'verbose_name': 'Contact Page SEO',
                'verbose_name_plural': 'Contact Page SEO',
            },
        ),
        migrations.CreateModel(
            name='FaqPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/faq/')),
            ],
            options={
                'verbose_name': 'Faq Page SEO',
                'verbose_name_plural': 'Faq Page SEO',
            },
        ),
        migrations.CreateModel(
            name='HomePageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/home/')),
            ],
            options={
                'verbose_name': 'Homepage SEO',
                'verbose_name_plural': 'Homepage SEO',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 30-60 aralığındadır.',
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                ('og_image', models.ImageField(upload_to='seo-images/services/')),
            ],
            options={
                'verbose_name': 'Services Page SEO',
                'verbose_name_plural': 'Services Page SEO',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'service',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='detail_page_seo',
                        to='service.service',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Service Detail Page SEO',
                'verbose_name_plural': 'Service Detail Page SEO',
            },
        ),
        migrations.CreateModel(
            name='BlogDetailPageSeo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'meta_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'meta_keywords_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_az',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_en',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'og_description_ru',
                    models.TextField(
                        help_text='Kontentin uzunluğu maksimum 50-160 aralığındadır.',
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(160),
                            django.core.validators.MinLengthValidator(50),
                        ],
                    ),
                ),
                (
                    'blog',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='detail_page_seo',
                        to='blog.blog',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Blog Detail Page SEO',
                'verbose_name_plural': 'Blog Detail Page SEO',
            },
        ),
    ]
