# Generated by Django 4.2.17 on 2025-05-13 11:49

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_download_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='background_color',
            field=models.CharField(
                choices=[('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue')],
                default='blue',
                max_length=20,
                verbose_name='Background color',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text='The content length is a maximum of 1000, minimum of 300.',
                validators=[
                    django.core.validators.MinLengthValidator(300),
                    django.core.validators.MaxLengthValidator(1000),
                ],
                verbose_name='Content',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text='The content length is a maximum of 1000, minimum of 300.',
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(300),
                    django.core.validators.MaxLengthValidator(1000),
                ],
                verbose_name='Content',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text='The content length is a maximum of 1000, minimum of 300.',
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(300),
                    django.core.validators.MaxLengthValidator(1000),
                ],
                verbose_name='Content',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text='The content length is a maximum of 1000, minimum of 300.',
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(300),
                    django.core.validators.MaxLengthValidator(1000),
                ],
                verbose_name='Content',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=200,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_az',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=200,
                null=True,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=200,
                null=True,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=200,
                null=True,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='png',
            field=models.FileField(
                help_text='Please upload a PNG file.(94x74px)',
                upload_to='services/',
                verbose_name='PNG file',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(
                help_text='The content length is a maximum of 160, minimum of 145.',
                validators=[
                    django.core.validators.MinLengthValidator(145),
                    django.core.validators.MaxLengthValidator(160),
                ],
                verbose_name='Short description',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_az',
            field=models.TextField(
                help_text='The content length is a maximum of 160, minimum of 145.',
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(145),
                    django.core.validators.MaxLengthValidator(160),
                ],
                verbose_name='Short description',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(
                help_text='The content length is a maximum of 160, minimum of 145.',
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(145),
                    django.core.validators.MaxLengthValidator(160),
                ],
                verbose_name='Short description',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(
                help_text='The content length is a maximum of 160, minimum of 145.',
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(145),
                    django.core.validators.MaxLengthValidator(160),
                ],
                verbose_name='Short description',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Leave blank to auto-generate.',
                max_length=500,
                null=True,
                verbose_name='Slug',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(
                help_text='The content length is a maximum of 60, minimum of 30.',
                max_length=60,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(30)],
                verbose_name='Title',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_az',
            field=models.CharField(
                help_text='The content length is a maximum of 60, minimum of 30.',
                max_length=60,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(30)],
                verbose_name='Title',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(
                help_text='The content length is a maximum of 60, minimum of 30.',
                max_length=60,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(30)],
                verbose_name='Title',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(
                help_text='The content length is a maximum of 60, minimum of 30.',
                max_length=60,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(30)],
                verbose_name='Title',
            ),
        ),
    ]
