# Generated by Django 4.2.17 on 2025-05-13 12:40

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        (
            'service',
            '0004_alter_service_options_alter_service_background_color_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(
                upload_to='services/images/',
                validators=[
                    utils.validators.validate_image.validate_image_extension,
                    utils.validators.validate_image.validate_image_size,
                ],
                verbose_name='Main photo',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='png',
            field=models.FileField(
                help_text='Please upload a PNG file.(94x74px)',
                upload_to='services/png/',
                verbose_name='PNG file',
            ),
        ),
    ]
