# Generated by Django 4.2.17 on 2025-05-13 13:22

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_image_alter_service_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(
                help_text='Please upload a PNG or JPG file',
                upload_to='services/images/',
                validators=[
                    utils.validators.validate_image.validate_image_extension,
                    utils.validators.validate_image.validate_image_size,
                ],
                verbose_name='Main photo',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='png',
            field=models.ImageField(
                help_text='Please upload a PNG file.(94x74px)',
                upload_to='services/png/',
                verbose_name='PNG file',
            ),
        ),
    ]
