# Generated by Django 4.2.17 on 2025-05-13 13:31

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_image_alter_service_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=30,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_az',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=30,
                null=True,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=30,
                null=True,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(
                help_text='The content length is a maximum of 30.',
                max_length=30,
                null=True,
                unique=True,
                verbose_name='Service name',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='png',
            field=models.ImageField(
                help_text='Please upload a PNG file.(94x74px)',
                upload_to='services/png/',
                validators=[utils.validators.validate_image.validate_image_size],
                verbose_name='PNG file',
            ),
        ),
    ]
