# Generated by Django 4.2.17 on 2025-05-14 20:24

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_name_alter_service_name_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(
                help_text='Please upload a PNG or JPG file',
                upload_to='services/images/',
                validators=[
                    utils.validators.validate_image.validate_image_extension,
                    utils.validators.validate_image.validate_image_size,
                    utils.validators.validate_image.validate_image_content,
                ],
                verbose_name='Main photo',
            ),
        ),
    ]
