# Generated by Django 4.2.17 on 2025-05-14 21:35

from django.db import migrations, models
import utils.validators.validate_image
import utils.validators.validate_png


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='png',
            field=models.ImageField(
                help_text='Please upload a PNG file.(94x74px)',
                upload_to='services/png/',
                validators=[
                    utils.validators.validate_image.validate_image_size,
                    utils.validators.validate_png.validate_png_extension,
                ],
                verbose_name='PNG file',
            ),
        ),
    ]
