# Generated by Django 4.2.17 on 2025-05-15 12:53

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import utils.validators.validate_google_map
import utils.validators.validate_phone
import utils.validators.validate_social_media
import utils.validators.validate_time


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'image',
                    models.ImageField(
                        help_text='Haqqımızda səhifəsində göstərilməsi üçün foto yükləyin',
                        upload_to='about/',
                        verbose_name='Foto',
                    ),
                ),
                (
                    'video_id',
                    models.CharField(
                        help_text='Nümunə: "https://www.youtube.com/watch?v=MKG_6BqnhpI" linkindən  "MKG_6BqnhpI" daxil edilməlidir',
                        max_length=11,
                        verbose_name='Video link id',
                    ),
                ),
                (
                    'content',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Haqqımızda səhifəsi üçün kontent',
                        verbose_name='Haqqımızda məlumat',
                    ),
                ),
                (
                    'content_az',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Haqqımızda səhifəsi üçün kontent',
                        null=True,
                        verbose_name='Haqqımızda məlumat',
                    ),
                ),
                (
                    'content_en',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Haqqımızda səhifəsi üçün kontent',
                        null=True,
                        verbose_name='Haqqımızda məlumat',
                    ),
                ),
                (
                    'content_ru',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Haqqımızda səhifəsi üçün kontent',
                        null=True,
                        verbose_name='Haqqımızda məlumat',
                    ),
                ),
                ('mission', models.TextField(verbose_name='Missiyamız')),
                ('mission_az', models.TextField(null=True, verbose_name='Missiyamız')),
                ('mission_en', models.TextField(null=True, verbose_name='Missiyamız')),
                ('mission_ru', models.TextField(null=True, verbose_name='Missiyamız')),
                ('vision', models.TextField(verbose_name='Görüşümüz')),
                ('vision_az', models.TextField(null=True, verbose_name='Görüşümüz')),
                ('vision_en', models.TextField(null=True, verbose_name='Görüşümüz')),
                ('vision_ru', models.TextField(null=True, verbose_name='Görüşümüz')),
                ('value', models.TextField(verbose_name='Dəyərlərimiz')),
                ('value_az', models.TextField(null=True, verbose_name='Dəyərlərimiz')),
                ('value_en', models.TextField(null=True, verbose_name='Dəyərlərimiz')),
                ('value_ru', models.TextField(null=True, verbose_name='Dəyərlərimiz')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        unique=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'subtitle',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        unique=True,
                        verbose_name='Alt başlıq',
                    ),
                ),
                (
                    'subtitle_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Alt başlıq',
                    ),
                ),
                (
                    'subtitle_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Alt başlıq',
                    ),
                ),
                (
                    'subtitle_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='Alt başlıq',
                    ),
                ),
                (
                    'description',
                    models.TextField(unique=True, verbose_name='Qısa izah'),
                ),
                (
                    'description_az',
                    models.TextField(null=True, unique=True, verbose_name='Qısa izah'),
                ),
                (
                    'description_en',
                    models.TextField(null=True, unique=True, verbose_name='Qısa izah'),
                ),
                (
                    'description_ru',
                    models.TextField(null=True, unique=True, verbose_name='Qısa izah'),
                ),
                (
                    'png',
                    models.ImageField(
                        help_text='PNG formatda daxil edin. Ölçü: 720x726px',
                        upload_to='banner/',
                        verbose_name='Banner foto',
                    ),
                ),
                (
                    'video_id',
                    models.CharField(
                        help_text='Nümunə: "https://www.youtube.com/watch?v=MKG_6BqnhpI" linkindən  "MKG_6BqnhpI" daxil edilməlidir',
                        max_length=11,
                        unique=True,
                        verbose_name='Video link id',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'first_name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 20-dir.',
                        max_length=20,
                        verbose_name='Ad',
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 20-dir.',
                        max_length=20,
                        verbose_name='Soyad',
                    ),
                ),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                (
                    'phone',
                    models.CharField(
                        help_text='Yalnız rəqəm daxil edin',
                        max_length=17,
                        validators=[
                            utils.validators.validate_phone.validate_phone_value
                        ],
                        verbose_name='Telefon nömrəsi',
                    ),
                ),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(verbose_name='Sual')),
                ('question_az', models.TextField(null=True, verbose_name='Sual')),
                ('question_en', models.TextField(null=True, verbose_name='Sual')),
                ('question_ru', models.TextField(null=True, verbose_name='Sual')),
                ('response', models.TextField(verbose_name='Cavab')),
                ('response_az', models.TextField(null=True, verbose_name='Cavab')),
                ('response_en', models.TextField(null=True, verbose_name='Cavab')),
                ('response_ru', models.TextField(null=True, verbose_name='Cavab')),
            ],
            options={
                'verbose_name': 'Tez-tez verilən sual',
                'verbose_name_plural': 'Tez-tez verilən suallar',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'site_name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(30)],
                        verbose_name='Site Name',
                    ),
                ),
                (
                    'logo',
                    models.ImageField(upload_to='logos/', verbose_name='Site Logo'),
                ),
                (
                    'favicon',
                    models.ImageField(upload_to='favicons/', verbose_name='Favicon'),
                ),
                (
                    'location',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        verbose_name='Məkan',
                    ),
                ),
                (
                    'location_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        verbose_name='Məkan',
                    ),
                ),
                (
                    'location_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        verbose_name='Məkan',
                    ),
                ),
                (
                    'location_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 100-dür.',
                        max_length=100,
                        null=True,
                        verbose_name='Məkan',
                    ),
                ),
                (
                    'number',
                    models.CharField(
                        help_text='Yalnız rəqəm daxil edin. Məsələn: +994123456789',
                        max_length=17,
                        validators=[
                            utils.validators.validate_phone.validate_phone_value
                        ],
                        verbose_name='Əlaqə nömrəsi',
                    ),
                ),
                (
                    'email',
                    models.EmailField(max_length=254, verbose_name='Email ünvanı'),
                ),
                (
                    'work_hours',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 13-dür. Nümunə: 09:00 - 18:00',
                        max_length=13,
                        validators=[utils.validators.validate_time.validate_work_hours],
                        verbose_name='İş saatları',
                    ),
                ),
                (
                    'map_url',
                    models.CharField(
                        help_text='Zəhmət olmasa, google məkanınızın "iframe" contentindən "src" attributunu daxil edin.',
                        max_length=500,
                        validators=[
                            utils.validators.validate_google_map.GoogleMapValidationError
                        ],
                        verbose_name='Xəritə',
                    ),
                ),
                (
                    'facebook',
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            utils.validators.validate_social_media.validate_facebook
                        ],
                        verbose_name='Facebook hesab linki',
                    ),
                ),
                (
                    'youtube',
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            utils.validators.validate_social_media.validate_youtube
                        ],
                        verbose_name='YouTube hesab linki',
                    ),
                ),
                (
                    'twitter',
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            utils.validators.validate_social_media.validate_twitter
                        ],
                        verbose_name='Twitter hesab linki',
                    ),
                ),
                (
                    'instagram',
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            utils.validators.validate_social_media.validate_instagram
                        ],
                        verbose_name='Instagram hesab linki',
                    ),
                ),
                (
                    'linkedin',
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            utils.validators.validate_social_media.validate_linkedin
                        ],
                        verbose_name='LinkedIn hesab linki',
                    ),
                ),
                (
                    'tiktok',
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            utils.validators.validate_social_media.validate_tiktok
                        ],
                        verbose_name='TikTok hesab linki',
                    ),
                ),
                (
                    'footer_description',
                    models.TextField(verbose_name='Footer hissədə göstəriləcək mətn'),
                ),
                (
                    'footer_description_az',
                    models.TextField(
                        null=True, verbose_name='Footer hissədə göstəriləcək mətn'
                    ),
                ),
                (
                    'footer_description_en',
                    models.TextField(
                        null=True, verbose_name='Footer hissədə göstəriləcək mətn'
                    ),
                ),
                (
                    'footer_description_ru',
                    models.TextField(
                        null=True, verbose_name='Footer hissədə göstəriləcək mətn'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'title',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'title_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        null=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'title_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        null=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'title_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        null=True,
                        verbose_name='Başlıq',
                    ),
                ),
                (
                    'video_link',
                    models.URLField(
                        help_text='Biz kimik bölməsinsdə göstərilməsi üçün video link',
                        verbose_name='Video linki',
                    ),
                ),
                (
                    'content',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Biz kimik bölməsi üçün kontent',
                        verbose_name='Biz kimik',
                    ),
                ),
                (
                    'content_az',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Biz kimik bölməsi üçün kontent',
                        null=True,
                        verbose_name='Biz kimik',
                    ),
                ),
                (
                    'content_en',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Biz kimik bölməsi üçün kontent',
                        null=True,
                        verbose_name='Biz kimik',
                    ),
                ),
                (
                    'content_ru',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text='Biz kimik bölməsi üçün kontent',
                        null=True,
                        verbose_name='Biz kimik',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Biz kimik',
                'verbose_name_plural': 'Biz kimik',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['created_at'], name='core_whowea_created_ea3282_idx'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Testimoinal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'client_image',
                    models.ImageField(
                        help_text="Foto '170x170px' ölçüsündə olmalıdır. ",
                        upload_to='testimonials/',
                        verbose_name='Müştəri fotosu',
                    ),
                ),
                (
                    'client_full_name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 20-dir.',
                        max_length=20,
                        verbose_name='Müştərinin ad, soyadı',
                    ),
                ),
                (
                    'client_profession',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=100,
                        verbose_name='Müştərinin peşəsi',
                    ),
                ),
                (
                    'client_profession_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=100,
                        null=True,
                        verbose_name='Müştərinin peşəsi',
                    ),
                ),
                (
                    'client_profession_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=100,
                        null=True,
                        verbose_name='Müştərinin peşəsi',
                    ),
                ),
                (
                    'client_profession_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 200-dür.',
                        max_length=100,
                        null=True,
                        verbose_name='Müştərinin peşəsi',
                    ),
                ),
                (
                    'client_comment',
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(150),
                            django.core.validators.MaxLengthValidator(155),
                        ],
                        verbose_name='Müştəri rəyi',
                    ),
                ),
                (
                    'client_comment_az',
                    models.TextField(
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(150),
                            django.core.validators.MaxLengthValidator(155),
                        ],
                        verbose_name='Müştəri rəyi',
                    ),
                ),
                (
                    'client_comment_en',
                    models.TextField(
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(150),
                            django.core.validators.MaxLengthValidator(155),
                        ],
                        verbose_name='Müştəri rəyi',
                    ),
                ),
                (
                    'client_comment_ru',
                    models.TextField(
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(150),
                            django.core.validators.MaxLengthValidator(155),
                        ],
                        verbose_name='Müştəri rəyi',
                    ),
                ),
                (
                    'star',
                    models.IntegerField(
                        help_text='5 ballıq sistem üzərindən dəyərləndirmə',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='Müştərinin verdiyi qiymət',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Müştəri rəyi',
                'verbose_name_plural': 'Müştəri rəyləri',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['created_at'], name='core_testim_created_a0169b_idx'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='StatisticalIndicator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'png',
                    models.FileField(
                        help_text='PNG formatda daxil edin',
                        upload_to='statistics/',
                        verbose_name='png',
                    ),
                ),
                (
                    'value',
                    models.IntegerField(verbose_name='Statistik göstəricinin dəyəri'),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        unique=True,
                        verbose_name='Statistik göstəricinin adı',
                    ),
                ),
                (
                    'name_az',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name='Statistik göstəricinin adı',
                    ),
                ),
                (
                    'name_en',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name='Statistik göstəricinin adı',
                    ),
                ),
                (
                    'name_ru',
                    models.CharField(
                        help_text='Kontentin uzunluğu maksimum 50-dir.',
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name='Statistik göstəricinin adı',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['created_at'], name='core_statis_created_ba77dc_idx'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Abunə',
                'verbose_name_plural': 'Abunələr',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['created_at'], name='core_newsle_created_1b62a7_idx'
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='faq',
            constraint=models.UniqueConstraint(
                fields=('question', 'response'), name='unique_faq_question_response'
            ),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(
                fields=['created_at'], name='core_contac_created_643cbb_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(
                fields=['created_at'], name='core_banner_created_3a3014_idx'
            ),
        ),
    ]
