name: Test and Commit Results
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Django unit tests and save results
        run: |
          cd app
          python manage.py test > test_results.txt

      - name: Commit test results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add test_results.txt
          git commit -m "Add test results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
