name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Set environment variables
        run: echo "SECRET_KEY=${{ secrets.MIRELDAR_BABAYEV_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Run Django unit tests
        env:
          DJANGO_SECRET_KEY: ${{ secrets.MIRELDAR_BABAYEV_SECRET_KEY }}
          DJANGO_SETTINGS_MODULE: config.settings
        run: |
          cd app
          python manage.py test

      - name: Generate test results
        run: |
          echo "Test results: Passed" > test_results.txt
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/shabnamadil/MireldarBabayev.git
      
      - name: Push changes
        run: |
          git add test_results.txt
          git commit -m "Add test results"
          git push origin tests