name: Issue Labeling

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add "triage" label to new issue
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "bug"