name: type
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - run: pip install --upgrade virtualenv pip setuptools
      - run: virtualenv .venv
      - run: source .venv/bin/activate
      - run: make dev-install
      - run: make type-check